version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - chatbot
  chatbot:
    build: ./services/app
    expose: 
      - 5001
    environment:
      - LIVE=1
      - DATABASE=sqlite
      - PYTHONUNBUFFER=1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}