"""Migration #2 Swapping Table Names

Revision ID: 5ee15a07d356
Revises: 55183dbfb8e4
Create Date: 2024-06-23 01:43:00.587473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ee15a07d356'
down_revision = '55183dbfb8e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('job_leave', 'old_job_leave')
    op.rename_table('job_system', 'old_job_system')
    op.rename_table('metrics', 'old_metrics')
    op.rename_table('users', 'old_users')
    op.rename_table('leave_records', 'old_leave_records')
    op.rename_table('message_confirm', 'old_message_confirm')
    op.rename_table('job_user', 'old_job_user')
    op.rename_table('message_forward', 'old_message_forward')
    op.rename_table('message_sent', 'old_message_sent')
    op.rename_table('message', 'old_message')
    op.rename_table('job_acq_token', 'old_job_acq_token')
    op.rename_table('job_sync_users', 'old_job_sync_users')
    op.rename_table('job_unknown', 'old_job_unknown')
    op.rename_table('job_sync_records', 'old_job_sync_records')
    op.rename_table('message_received', 'old_message_received')
    op.rename_table('job_es', 'old_job_es')
    op.rename_table('job_leave_cancel', 'old_job_leave_cancel')
    op.rename_table('job', 'old_job')
    op.rename_table('job_am_report', 'old_job_am_report')

    op.rename_table('new_message', 'message')
    op.rename_table('new_users', 'users')
    op.rename_table('new_job', 'job')
    op.rename_table('new_job_leave', 'job_leave')
    op.rename_table('new_leave_records', 'leave_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('message', 'new_message')
    op.rename_table('users', 'new_users')
    op.rename_table('job', 'new_job')
    op.rename_table('job_leave', 'new_job_leave')
    op.rename_table('leave_records', 'new_leave_records')

    op.rename_table('old_job_leave', 'job_leave')
    op.rename_table('old_job_system', 'job_system')
    op.rename_table('old_metrics', 'metrics')
    op.rename_table('old_users', 'users')
    op.rename_table('old_leave_records', 'leave_records')
    op.rename_table('old_message_confirm', 'message_confirm')
    op.rename_table('old_job_user', 'job_user')
    op.rename_table('old_message_forward', 'message_forward')
    op.rename_table('old_message_sent', 'message_sent')
    op.rename_table('old_message', 'message')
    op.rename_table('old_job_acq_token', 'job_acq_token')
    op.rename_table('old_job_sync_users', 'job_sync_users')
    op.rename_table('old_job_unknown', 'job_unknown')
    op.rename_table('old_job_sync_records', 'job_sync_records')
    op.rename_table('old_message_received', 'message_received')
    op.rename_table('old_job_es', 'job_es')
    op.rename_table('old_job_leave_cancel', 'job_leave_cancel')
    op.rename_table('old_job', 'job')
    op.rename_table('old_job_am_report', 'job_am_report')

    
    