name: chatbot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.2.1
  - spacy=3.6.1
  - numpy=1.26.0
  - keras
  - matplotlib=3.8.0
  - pandas=2.1.0
  - nltk=3.8.1
  - scikit-learn=1.3.0
  - jupyter=1.0.0
  - tensorflow=2.12.1
  - seaborn=0.12.2
  - gunicorn=21.2.0
  - openpyxl=3.1.2
  - flask=2.3.3
  - twilio=8.9.0
  - word2number=1.1
  - sqlite=3.43.0