name: chatbot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - PyMuPDF
  - spacy
  - numpy
  - keras
  - matplotlib
  - pandas
  - nltk
  - scikit-learn
  - jupyter
  - tensorflow
  - seaborn
  - gunicorn
  - openpyxl
  - flask
  - twilio
  - word2number
  - sqlite
  - msal
  - python-dotenv
  - flask-sqlalchemy
  - pytesseract
  - pytorch
  - fire
  - sentencepiece
  - fairscale
  - elasticsearch-dsl>=8.0.0,<9.0.0
  - elasticsearch=8.10.0
  - python-docx
  - pdfminer.six
  - pdfplumber
  - pytesseract
  - Pillow