"""Migration #3 Delete Old Tables

Revision ID: 7c843959cf4f
Revises: 5ee15a07d356
Create Date: 2024-06-23 02:03:37.953128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c843959cf4f'
down_revision = '5ee15a07d356'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_leave_records')
    op.drop_table('old_users')
    op.drop_table('old_metrics')
    op.drop_table('old_job_am_report')
    op.drop_table('old_job_leave_cancel')
    op.drop_table('old_job_user')
    op.drop_table('old_message')
    op.drop_table('old_job_unknown')
    op.drop_table('old_job_system')
    op.drop_table('old_message_confirm')
    op.drop_table('old_job_sync_records')
    op.drop_table('old_message_sent')
    op.drop_table('old_message_forward')
    op.drop_table('old_job_leave')
    op.drop_table('old_job')
    op.drop_table('old_message_received')
    op.drop_table('old_job_acq_token')
    op.drop_table('old_job_sync_users')
    op.drop_table('old_job_es')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_job_es',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('helpful', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('answered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_user.job_no'], name='job_es_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_es_pkey')
    )
    op.create_table('old_job_sync_users',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_system.job_no'], name='job_sync_users_job_no_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_no', name='job_sync_users_pkey')
    )
    op.create_table('old_job_acq_token',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_system.job_no'], name='job_acq_token_job_no_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_no', name='job_acq_token_pkey')
    )
    op.create_table('old_message_received',
    sa.Column('sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('reply_sid', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['old_message.sid'], name='message_received_sid_fkey'),
    sa.PrimaryKeyConstraint('sid', name='message_received_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_job',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('job_no', name='job_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_job_leave',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('local_db_updated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('forwards_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_user.job_no'], name='job_leave_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_leave_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_message_forward',
    sa.Column('sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('to_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['old_message_sent.sid'], name='message_forward_sid_fkey'),
    sa.PrimaryKeyConstraint('sid', name='message_forward_pkey')
    )
    op.create_table('old_message_sent',
    sa.Column('sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_expecting_reply', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['old_message.sid'], name='message_sent_sid_fkey'),
    sa.PrimaryKeyConstraint('sid', name='message_sent_pkey')
    )
    op.create_table('old_job_sync_records',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('forwards_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_system.job_no'], name='job_sync_records_job_no_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_no', name='job_sync_records_pkey')
    )
    op.create_table('old_message_confirm',
    sa.Column('sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('ref_msg_sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('_decision', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['old_message_received.sid'], name='message_confirm_sid_fkey'),
    sa.PrimaryKeyConstraint('sid', name='message_confirm_pkey')
    )
    op.create_table('old_job_system',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('root_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['old_job.job_no'], name='job_system_job_no_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_no', name='job_system_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_job_unknown',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('from_no', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['old_job.job_no'], name='job_unknown_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_unknown_pkey')
    )
    op.create_table('old_message',
    sa.Column('sid', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('seq_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['old_job.job_no'], name='message_job_no_fkey'),
    sa.PrimaryKeyConstraint('sid', name='message_pkey')
    )
    op.create_table('old_job_user',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_no'], ['old_job.job_no'], name='job_user_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_job_leave_cancel',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('initial_job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['initial_job_no'], ['old_job_leave.job_no'], name='job_leave_cancel_initial_job_no_fkey'),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_leave.job_no'], name='job_leave_cancel_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_leave_cancel_pkey'),
    sa.UniqueConstraint('initial_job_no', name='job_leave_cancel_initial_job_no_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_job_am_report',
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('forwards_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_system.job_no'], name='job_am_report_job_no_fkey'),
    sa.PrimaryKeyConstraint('job_no', name='job_am_report_pkey')
    )
    op.create_table('old_metrics',
    sa.Column('_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_successful_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_job_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_successful_job_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['last_job_no'], ['old_job.job_no'], name='metrics_last_job_no_fkey'),
    sa.ForeignKeyConstraint(['last_successful_job_no'], ['old_job.job_no'], name='metrics_last_successful_job_no_fkey'),
    sa.PrimaryKeyConstraint('_type', name='metrics_pkey')
    )
    op.create_table('old_users',
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dept', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reporting_officer_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('is_global_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_dept_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reporting_officer_name'], ['old_users.name'], name='users_reporting_officer_name_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name', name='users_pkey'),
    sa.UniqueConstraint('number', name='users_number_key')
    )
    op.create_table('old_leave_records',
    sa.Column('id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('job_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cancelled_job_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sync_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cancelled_job_no'], ['old_job_leave_cancel.job_no'], name='leave_records_cancelled_job_no_fkey'),
    sa.ForeignKeyConstraint(['job_no'], ['old_job_leave.job_no'], name='leave_records_job_no_fkey'),
    sa.PrimaryKeyConstraint('id', name='leave_records_pkey')
    )
    # ### end Alembic commands ###
